[2019-04-23 09:54:36 -0400] [73777] [CRITICAL] WORKER TIMEOUT (pid:73781)
[2019-04-23 09:56:25 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73925)
[2019-04-23 09:56:25 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73919)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73920)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73921)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73922)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73923)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73924)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73990)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73926)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73927)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73991)
[2019-04-23 10:08:54 -0400] [74159] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74160] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74161] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74162] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74163] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74164] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74166] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74165] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74167] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:14 -0400] [74200] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:14 -0400] [74201] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:14 -0400] [74202] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74203] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74204] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74205] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74206] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74207] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74208] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74264] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74265] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74266] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74267] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74268] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74270] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74269] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74271] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74272] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 16:04:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75845)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75846)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75851)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75853)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75855)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75858)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75859)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75860)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75861)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:77533)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78635)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78636)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78637)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78638)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78639)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78640)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78641)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78642)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78643)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80075)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80076)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80077)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80078)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80080)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80081)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80082)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80083)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80084)
[2019-04-23 19:37:40 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80623)
[2019-04-23 19:37:40 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80632)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80910)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80911)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80624)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80626)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80627)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80628)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80629)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80630)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80631)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81615)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81616)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81618)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81619)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81620)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81621)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81622)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81623)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81624)
[2019-04-24 07:12:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82216)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82276)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82218)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82219)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82220)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82221)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82223)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82225)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82226)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82227)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83491)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83492)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83493)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83494)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83495)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83496)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83497)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83498)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83499)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83584)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83585)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83586)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83587)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83588)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83589)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83590)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83591)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83592)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84343)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84344)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84345)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84348)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84513)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84514)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84515)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84516)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84346)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84347)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84349)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84350)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84351)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86080)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86081)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86082)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86083)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86084)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86085)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86086)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86079)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86078)
[2019-04-24 14:44:36 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87239)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87240)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87241)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87242)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87243)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87244)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87245)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87237)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87238)
[2019-04-24 16:53:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88526)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88525)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88528)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88529)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88530)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88531)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88532)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88533)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88527)
[2019-04-24 19:22:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89090)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89091)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89092)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89094)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89083)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89084)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89086)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89087)
[2019-04-24 19:41:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91904)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91905)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91906)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91907)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89093)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91900)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91901)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91902)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91903)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92032)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92024)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92025)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92026)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92027)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92028)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92029)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92030)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92031)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92288)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92290)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92291)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92292)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92293)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92294)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92289)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92297)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92295)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92342)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92343)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92344)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92345)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92346)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92347)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92389)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92390)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92391)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92392)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92394)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92348)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92349)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92350)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92435)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92436)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92437)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92438)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92439)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92440)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92441)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92442)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92393)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92490)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92491)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92492)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92493)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92494)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92495)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92496)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92497)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92498)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92544)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92536)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92537)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92538)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92539)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92540)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92541)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92542)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92543)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92580)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92581)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92582)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92583)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92585)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92586)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92587)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92588)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92589)
[2019-04-25 00:52:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92633)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92686)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92634)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92635)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92636)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92637)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92638)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92639)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92640)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92641)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92701)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92702)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92703)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92704)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92705)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92706)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92707)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92708)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92700)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92754)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92755)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92756)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92757)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92758)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92759)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92760)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92761)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92762)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92806)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92807)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92808)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92810)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92811)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92812)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92813)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92814)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92815)
[2019-04-25 05:12:26 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92876)
[2019-04-25 05:12:26 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92877)
[2019-04-25 05:12:26 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92878)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92929)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92930)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92931)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92879)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92882)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92885)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92886)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92887)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92888)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92953)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92954)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92955)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92956)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92957)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92958)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92959)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92960)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92961)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92999)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93000)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93001)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93002)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93003)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93004)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93005)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93006)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93007)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93056)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93057)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93058)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93050)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93051)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93052)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93053)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93054)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93055)
[2019-04-25 08:18:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93101)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93102)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93103)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93104)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93105)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93106)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93107)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93108)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93109)
[2019-04-25 09:31:48 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93369)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93366)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93367)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93368)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93364)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93370)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93371)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93372)
[2019-04-25 09:31:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93365)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94441)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94442)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94443)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94444)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94445)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94446)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94448)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94449)
[2019-04-25 11:09:44 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:94450)
[2019-04-25 11:53:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96388)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96389)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96390)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96391)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96392)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96393)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96394)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96395)
[2019-04-25 11:53:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96396)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96962)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96963)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96964)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96965)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96966)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96967)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96968)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96969)
[2019-04-25 13:00:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:96970)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97024)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97025)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97026)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97027)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97028)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97029)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97030)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97031)
[2019-04-25 15:03:28 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:97032)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99298)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99299)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99300)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99301)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99302)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99297)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99304)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99305)
[2019-04-25 15:57:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:99303)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:544)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:522)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:523)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:525)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:526)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:528)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:521)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:536)
[2019-04-25 16:12:07 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:538)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:683)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:684)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:685)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:686)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:687)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:688)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:689)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:690)
[2019-04-25 16:20:06 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:691)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:802)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:803)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:806)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:807)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:808)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:809)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:810)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:811)
[2019-04-25 16:33:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:812)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:867)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:868)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:869)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:870)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:871)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:873)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:874)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:875)
[2019-04-25 16:40:30 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:876)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:928)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:929)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:930)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:931)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:933)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:934)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:935)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:936)
[2019-04-25 16:46:57 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:937)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1292)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1293)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1294)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1295)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1296)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1297)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1298)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1299)
[2019-04-25 17:07:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1300)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1349)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1350)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1351)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1352)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1353)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1354)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1355)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1357)
[2019-04-25 17:16:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1358)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1425)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1426)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1428)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1429)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1430)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1431)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1432)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1433)
[2019-04-25 17:33:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1434)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1611)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1612)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1613)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1614)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1615)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1616)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1617)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1618)
[2019-04-25 19:48:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1619)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1671)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1673)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1676)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1681)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1682)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1683)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1684)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1685)
[2019-04-25 23:03:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:1686)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3277)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3278)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3279)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3280)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3281)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3282)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3283)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3284)
[2019-04-26 07:33:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3285)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3296)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3312)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3300)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3301)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3302)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3307)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3308)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3310)
[2019-04-26 07:46:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3295)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3346)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3347)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3348)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3349)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3350)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3351)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3352)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3353)
[2019-04-26 09:19:33 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:3354)
[2019-04-26 09:45:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5593)
[2019-04-26 09:45:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5590)
[2019-04-26 09:45:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5592)
[2019-04-26 09:45:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5594)
[2019-04-26 09:45:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5595)
[2019-04-26 09:45:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5596)
[2019-04-26 10:13:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6107)
[2019-04-26 10:13:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6109)
[2019-04-26 10:13:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6108)
[2019-04-26 10:13:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6106)
[2019-04-26 10:13:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6110)
[2019-04-26 10:13:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6111)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6449)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6450)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6451)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6452)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5589)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6454)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5591)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:5588)
[2019-04-26 12:02:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:6453)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7790)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7791)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7792)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7793)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7794)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7795)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7796)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7797)
[2019-04-26 12:15:21 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7798)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7851)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7852)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7853)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7854)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7855)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7856)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7857)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7858)
[2019-04-26 12:35:43 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:7859)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8339)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8337)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8338)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8340)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8341)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8342)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8343)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8344)
[2019-04-26 13:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8345)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8465)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8466)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8467)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8468)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8469)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8470)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8471)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8472)
[2019-04-26 14:08:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:8473)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9303)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9304)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9305)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9306)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9307)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9308)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9309)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9310)
[2019-04-26 15:02:59 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9311)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9485)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9486)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9487)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9488)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9489)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9490)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9491)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9492)
[2019-04-26 18:14:22 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:9493)
[2019-04-26 21:40:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10346)
[2019-04-27 06:41:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10725)
[2019-04-27 09:24:52 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10745)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10773)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10347)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10348)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10349)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10350)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10351)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10352)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10353)
[2019-04-27 10:53:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:10354)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11473)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11474)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11476)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11477)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11478)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11479)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11480)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11481)
[2019-04-27 14:58:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:11482)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12269)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12270)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12271)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12272)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12273)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12274)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12275)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12276)
[2019-04-27 20:51:03 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:12277)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13809)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13810)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13811)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13812)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13813)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13814)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13815)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13816)
[2019-04-28 17:11:47 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13817)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13909)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13910)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13911)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13912)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13913)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13914)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13915)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13916)
[2019-04-29 00:04:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:13917)
[2019-04-29 08:47:49 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16757)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16808)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16749)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16750)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16751)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16752)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16753)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16754)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16755)
[2019-04-29 09:01:45 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:16756)
[2019-04-29 10:45:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17152)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17153)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17154)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18179)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17146)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17147)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17148)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17149)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17150)
[2019-04-29 11:04:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:17151)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18368)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18369)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18370)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18362)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18363)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18364)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18365)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18366)
[2019-04-29 11:53:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:18367)
[2019-04-29 20:19:49 +0000] [4862] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-29 20:44:31 +0000] [4854] [CRITICAL] WORKER TIMEOUT (pid:4861)
[2019-04-29 20:50:41 +0000] [4854] [CRITICAL] WORKER TIMEOUT (pid:12534)
[2019-04-29 21:00:04 +0000] [4854] [CRITICAL] WORKER TIMEOUT (pid:4862)
[2019-04-29 21:00:41 +0000] [4854] [CRITICAL] WORKER TIMEOUT (pid:12537)
[2019-04-30 10:03:20,188] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3YGXWBAF71DSPB3YFCPRXDXBMWJC4D'], 'workerId': [u'A191V7PT3DQKDP'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:03:21 +0000] [24570] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 165, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 156, in get_data
    data = unreader.read()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
error: [Errno 4] Interrupted system call
[2019-04-30 10:03:21 +0000] [24571] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 165, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 156, in get_data
    data = unreader.read()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
error: [Errno 4] Interrupted system call
[2019-04-30 10:03:45,965] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3X1FV8S5JYN4002I1UMXWUI3X88GV3'], 'workerId': [u'A4T4577P6JL6R'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:14:35 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24570)
[2019-04-30 10:15:06 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24573)
[2019-04-30 10:15:37 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24618)
[2019-04-30 10:16:08 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24571)
[2019-04-30 10:16:40 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24620)
[2019-04-30 10:17:11 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24624)
[2019-04-30 10:17:42 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24574)
[2019-04-30 10:18:12 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24629)
[2019-04-30 10:18:43 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24626)
[2019-04-30 10:19:13 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24633)
[2019-04-30 10:19:44 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24635)
[2019-04-30 10:20:15 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24631)
[2019-04-30 10:20:46 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24622)
[2019-04-30 10:21:17 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24576)
[2019-04-30 10:21:48 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24637)
[2019-04-30 10:22:05 +0000] [24639] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 165, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 156, in get_data
    data = unreader.read()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
error: [Errno 4] Interrupted system call
[2019-04-30 10:22:05 +0000] [24646] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 165, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 156, in get_data
    data = unreader.read()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
error: [Errno 4] Interrupted system call
[2019-04-30 10:22:36 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24648)
[2019-04-30 10:23:07 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24642)
[2019-04-30 10:23:38 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24639)
[2019-04-30 10:24:08 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24646)
[2019-04-30 10:24:39 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24687)
[2019-04-30 10:25:10 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24644)
[2019-04-30 10:25:13,036] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3VNL7UK1XGFJ982YLFG0DRU6Z8XFTS'], 'workerId': [u'A298GPAEHRSV9J'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:25:33,165] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'39PAAFCODNW855OOLUL4VDXSN1FTVM'], 'workerId': [u'A1JYOZ111S9MIR'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:25:40 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24689)
[2019-04-30 10:26:11 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24695)
[2019-04-30 10:26:41 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24699)
[2019-04-30 10:27:11 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24693)
[2019-04-30 10:27:42 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24697)
[2019-04-30 10:28:13 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24701)
[2019-04-30 10:28:44 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24707)
[2019-04-30 10:29:15 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24691)
[2019-04-30 10:29:46 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24703)
[2019-04-30 10:30:17 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25109)
[2019-04-30 10:30:48 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25111)
[2019-04-30 10:31:18 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24710)
[2019-04-30 10:31:50 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25115)
[2019-04-30 10:32:20 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25117)
[2019-04-30 10:32:51 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25107)
[2019-04-30 10:33:21 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25121)
[2019-04-30 10:33:52 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25119)
[2019-04-30 10:34:22 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25126)
[2019-04-30 10:34:53 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25123)
[2019-04-30 10:35:24 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25113)
[2019-04-30 10:35:55 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25128)
[2019-04-30 10:36:25 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25145)
[2019-04-30 10:36:56 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:24705)
[2019-04-30 10:37:27 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25150)
[2019-04-30 10:37:58 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25143)
[2019-04-30 10:38:29 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25154)
[2019-04-30 10:38:39,719] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3ZV9H2YQQE3GLDQZWPK9Z2C80CE3W1'], 'workerId': [u'A3JVG39ZC5U3AE'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:38:56,069] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3M0NZ3JDP2UNTNI8LVS9D34AVA15ZB'], 'workerId': [u'A1ZGUINLRI34VO'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:38:59 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25147)
[2019-04-30 10:39:17,209] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3M0NZ3JDP2UNTNI8LVS9D34AVA15ZB'], 'workerId': [u'A1ZGUINLRI34VO'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:39:30 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25156)
[2019-04-30 10:40:01 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25160)
[2019-04-30 10:40:32 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25140)
[2019-04-30 10:41:03 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25167)
[2019-04-30 10:41:34 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25174)
[2019-04-30 10:42:04 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25158)
[2019-04-30 10:42:35 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25193)
[2019-04-30 10:43:06 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25152)
[2019-04-30 10:43:36 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25200)
[2019-04-30 10:44:07 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25198)
[2019-04-30 10:44:38 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25204)
[2019-04-30 10:45:09 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25196)
[2019-04-30 10:45:40 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25181)
[2019-04-30 10:46:11 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25202)
[2019-04-30 10:46:42 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25206)
[2019-04-30 10:47:13 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25211)
[2019-04-30 10:47:44 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25209)
[2019-04-30 10:48:14 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25255)
[2019-04-30 10:48:45 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25223)
[2019-04-30 10:49:16 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25269)
[2019-04-30 10:49:46 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25267)
[2019-04-30 10:50:17 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25248)
[2019-04-30 10:50:48 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25276)
[2019-04-30 10:51:18 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25274)
[2019-04-30 10:51:49 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25241)
[2019-04-30 10:52:19 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25271)
[2019-04-30 10:52:43,412] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3RSDURM96BINKG1W0AJT3Q1L29VEYT'], 'workerId': [u'A2NGJ8J03WB1KS'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:52:50 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25283)
[2019-04-30 10:53:21 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25278)
[2019-04-30 10:53:38 +0000] [25280] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 165, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 156, in get_data
    data = unreader.read()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
error: [Errno 4] Interrupted system call
[2019-04-30 10:53:43 +0000] [25318] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 165, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 156, in get_data
    data = unreader.read()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
error: [Errno 4] Interrupted system call
[2019-04-30 10:53:43 +0000] [25288] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 165, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/message.py", line 156, in get_data
    data = unreader.read()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/abeukers/.conda/envs/psiturk-latest/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
error: [Errno 4] Interrupted system call
[2019-04-30 10:54:14 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25300)
[2019-04-30 10:54:45 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25318)
[2019-04-30 10:55:15 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25285)
[2019-04-30 10:55:46 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25352)
[2019-04-30 10:56:17 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25340)
[2019-04-30 10:56:48 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25361)
[2019-04-30 10:57:18 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25359)
[2019-04-30 10:57:49 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25365)
[2019-04-30 10:58:21 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25367)
[2019-04-30 10:58:51 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25369)
[2019-04-30 10:58:52,822] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3NLZY2D53QLSHKK2QMP33ZO3CXFLQK'], 'workerId': [u'A1PT6264PIYFCI'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 10:59:22 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25363)
[2019-04-30 10:59:53 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25768)
[2019-04-30 11:00:23,977] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3NLZY2D53QLSHKK2QMP33ZO3CXFLQK'], 'workerId': [u'A2XX2QRRBNC0Y7'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 11:00:24 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25288)
[2019-04-30 11:00:54 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25528)
[2019-04-30 11:01:26 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25772)
[2019-04-30 11:01:57 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25280)
[2019-04-30 11:02:27 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25792)
[2019-04-30 11:02:58 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25777)
[2019-04-30 11:03:22,959] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3M0NZ3JDP2UNTNI8LVS9D34AVA15ZB'], 'workerId': [u'AOWW3URQNRJ6U'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 11:03:29 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25770)
[2019-04-30 11:03:59 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25798)
[2019-04-30 11:04:30 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25775)
[2019-04-30 11:08:26 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25804)
[2019-04-30 11:12:57 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25794)
[2019-04-30 11:15:32,745] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3MB8LZR5BGP66HM7DH567DCUDR7LKC'], 'workerId': [u'A1VFRCYMWGWWCZ'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 11:20:23,137] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3ZV9H2YQQE3GLDQZWPK9Z2C80CE3W1'], 'workerId': [u'A1BVG13MHBM1YD'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 11:23:36,879] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3WS1NTTKEZ8ITZ57NDSQTGS12XVF0B'], 'workerId': [u'A289DF24X3Q8JZ'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 11:40:25 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25802)
[2019-04-30 12:04:42,456] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3NL0RFNU0GJA89FM7P6PLWAJR5HK4N'], 'workerId': [u'A2R72PEQOZAINO'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 12:38:15 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25800)
[2019-04-30 12:51:41,474] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3QRYMNZ7FZDVX0FFJ3ZDLW3F1ZSTNM'], 'workerId': [u'A29V2XPA9H2NAN'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 13:33:56,211] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'34MAJL3QP5J4CB7FMJEQ4ATHGKP43S'], 'workerId': [u'A1XVEKS9O73ERE'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 13:38:02 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25811)
[2019-04-30 13:45:50 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:27279)
[2019-04-30 13:54:38 +0000] [24566] [CRITICAL] WORKER TIMEOUT (pid:25808)
[2019-04-30 13:55:17,892] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3TMSXRD2X7WKBACK9L6QB9XB2SR1WY'], 'workerId': [u'A1YSYI926BBOHW'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 14:01:17,118] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'323Q6SJS8JCT4ZB3LLZBZ8RIOFSFHA'], 'workerId': [u'A2OEDX14YO8EFJ'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 15:15:53,201] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3NGI5ARFTU1UR1FJXZSVJFPF9WB1PS'], 'workerId': [u'A24M9OW53CLT94'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 16:50:29,888] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'386PBUZZXGTBVXGPVW5U6YCHY48LJI'], 'workerId': [u'A1SLJKNSNHOJRN'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 18:00:34,409] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'31Q0U3WYDQB5LVBJ1DYEJTYU92C17S'], 'workerId': [u'A3ROADR7T6811'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
[2019-04-30 18:20:48,272] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'31UV0MXWNR81YXTYLR4ND81KZYLI5F'], 'workerId': [u'AA402T4YY1S7N'], 'hitId': [u'337F8MIIMZ959ZBPDUR5ESZOL5240K'], 'mode': [u'live']}
